agents:
    trae_agent:
        enable_lakeview: false
        model: trae_agent_model
        max_steps: 200
        tools:
            - bash
            - str_replace_based_edit_tool
            - sequentialthinking
            - task_done
            - ckg

model_providers:
    doubao:
        api_key: sk-1195008f8a904287948b4c3a5fbb0d63
        provider: doubao
        base_url: https://api.deepseek.com/v1

models:
    trae_agent_model:
        model_provider: doubao
        model: deepseek-reasoner
        max_tokens: 8192
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 1
        parallel_tool_calls: true
